# Site settings
title: "Blog Test Release"
email: daniel.siwiec@gmail.com
description: Coding and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  danielsiwiec

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      author: Daniel Siwiec
      layout: "post"
